WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600

COLOR_FOREGROUND = (75, 75, 75)
COLOR_BACKGROUND = (255, 255, 255)

TILE_WIDTH = 32
TILE_HEIGHT = 48

VIEW_TILE_SIZE = (9, 9)
VIEW_WIDTH = TILE_WIDTH * VIEW_TILE_SIZE[0]
VIEW_HEIGHT = TILE_HEIGHT * VIEW_TILE_SIZE[1]
VIEW_ORIGIN = ((WINDOW_WIDTH - VIEW_WIDTH) // 2, (WINDOW_HEIGHT - VIEW_HEIGHT) // 2)

VIEW_OUTPUT_GAP = 10

OUTPUT_ORIGIN = (VIEW_ORIGIN[0], VIEW_ORIGIN[1] + VIEW_HEIGHT + VIEW_OUTPUT_GAP)
